domainFile: domains/cell-based/brainman.pddl
problemFile: problem.pddl
domainName: VGDLGame
gameElementsCorrespondence:
  floor:
  - (at ?c ?floor)
  - (last-at ?c ?floor)
  avatar:
  - (at ?c ?avatar)
  - (last-at ?c ?avatar)
  gem:
  - (at ?c ?gem)
  - (last-at ?c ?gem)
  green:
  - (at ?c ?green)
  - (last-at ?c ?green)
  red:
  - (at ?c ?red)
  - (last-at ?c ?red)
  blue:
  - (at ?c ?blue)
  - (last-at ?c ?blue)
  key:
  - (at ?c ?key)
  - (last-at ?c ?key)
  keym:
  - (at ?c ?keym)
  - (last-at ?c ?keym)
  - (keym-moved ?keym)
  exit:
  - (at ?c ?exit)
  - (last-at ?c ?exit)
  door:
  - (at ?c ?door)
  - (last-at ?c ?door)
  boulder:
  - (at ?c ?boulder)
  - (last-at ?c ?boulder)
  wall:
  - (at ?c ?wall)
  - (last-at ?c ?wall)
variablesTypes:
  ?floor: floor
  ?avatar: avatar
  ?gem: gem
  ?green: green
  ?red: red
  ?blue: blue
  ?key: key
  ?keym: keym
  ?exit: exit
  ?door: door
  ?boulder: boulder
  ?wall: wall
  ?c: cell
cellVariable: ?c
avatarVariable: ?avatar
orientation:
  avatar: FIND
orientationCorrespondence:
  UP: (oriented-up ?object)
  DOWN: (oriented-down ?object)
  LEFT: (oriented-left ?object)
  RIGHT: (oriented-right ?object)
connections:
  UP: (connected-up ?c ?u)
  DOWN: (connected-down ?c ?d)
  LEFT: (connected-left ?c ?l)
  RIGHT: (connected-right ?c ?r)
actionsCorrespondence:
  AVATAR_ACTION_MOVE_UP: ACTION_UP
  AVATAR_ACTION_MOVE_DOWN: ACTION_DOWN
  AVATAR_ACTION_MOVE_LEFT: ACTION_LEFT
  AVATAR_ACTION_MOVE_RIGHT: ACTION_RIGHT
  AVATAR_ACTION_TURN_UP: ACTION_UP
  AVATAR_ACTION_TURN_DOWN: ACTION_DOWN
  AVATAR_ACTION_TURN_LEFT: ACTION_LEFT
  AVATAR_ACTION_TURN_RIGHT: ACTION_RIGHT
  AVATAR_ACTION_NIL: ACTION_NIL
additionalPredicates:
- (turn-avatar)
- (turn-sprites)
- (turn-interactions)
- (turn-keym-move)
- (finished-turn-keym-move)
addDeadObjects:
  key: 10
  keym: 10
goals: 
- goalPredicate: (turn-avatar)
  priority: 1
  saveGoal: no
