domainFile: domains/cell-based/catapults.pddl
problemFile: problem.pddl
domainName: VGDLGame
gameElementsCorrespondence:
  floor:
  - (at ?c ?floor)
  - (last-at ?c ?floor)
  water:
  - (at ?c ?water)
  - (last-at ?c ?water)
  catapult:
  - (at ?c ?catapult)
  - (last-at ?c ?catapult)
  southfacing:
  - (at ?c ?southfacing)
  - (last-at ?c ?southfacing)
  northfacing:
  - (at ?c ?northfacing)
  - (last-at ?c ?northfacing)
  eastfacing:
  - (at ?c ?eastfacing)
  - (last-at ?c ?eastfacing)
  westfacing:
  - (at ?c ?westfacing)
  - (last-at ?c ?westfacing)
  avatar:
  - (at ?c ?avatar)
  - (last-at ?c ?avatar)
  moving:
  - (at ?c ?moving)
  - (last-at ?c ?moving)
  bullet:
  - (at ?c ?bullet)
  - (last-at ?c ?bullet)
  north:
  - (at ?c ?north)
  - (last-at ?c ?north)
  south:
  - (at ?c ?south)
  - (last-at ?c ?south)
  east:
  - (at ?c ?east)
  - (last-at ?c ?east)
  west:
  - (at ?c ?west)
  - (last-at ?c ?west)
  goal:
  - (at ?c ?goal)
  - (last-at ?c ?goal)
  wall:
  - (at ?c ?wall)
  - (last-at ?c ?wall)
variablesTypes:
  ?floor: floor
  ?water: water
  ?catapult: catapult
  ?southfacing: southfacing
  ?northfacing: northfacing
  ?eastfacing: eastfacing
  ?westfacing: westfacing
  ?avatar: avatar
  ?moving: moving
  ?bullet: bullet
  ?north: north
  ?south: south
  ?east: east
  ?west: west
  ?goal: goal
  ?wall: wall
  ?c: cell
cellVariable: ?c
avatarVariable: ?moving
orientation:
  southfacing: DOWN
  northfacing: UP
  eastfacing: RIGHT
  westfacing: LEFT
  north: UP
  south: DOWN
  east: RIGHT
  west: LEFT
  moving: NONE
orientationCorrespondence:
  UP: (oriented-up ?object)
  DOWN: (oriented-down ?object)
  LEFT: (oriented-left ?object)
  RIGHT: (oriented-right ?object)
connections:
  UP: (connected-up ?c ?u)
  DOWN: (connected-down ?c ?d)
  LEFT: (connected-left ?c ?l)
  RIGHT: (connected-right ?c ?r)
actionsCorrespondence:
  AVATAR_ACTION_MOVE_UP: ACTION_UP
  AVATAR_ACTION_MOVE_DOWN: ACTION_DOWN
  AVATAR_ACTION_MOVE_LEFT: ACTION_LEFT
  AVATAR_ACTION_MOVE_RIGHT: ACTION_RIGHT
  AVATAR_ACTION_NIL: ACTION_NIL
additionalPredicates:
- (turn-avatar)
- (turn-sprites)
- (turn-interactions)
addDeadObjects:
  moving: 10
  west: 10
  east: 10
  south: 10
  north: 10
goals: 
- goalPredicate: (turn-avatar)
  priority: 1
  saveGoal: no
