domainFile: domains/cell-based/sokoban.pddl
problemFile: problem.pddl
domainName: VGDLGame
gameElementsCorrespondence:
  floor:
  - (at ?c ?floor)
  - (last-at ?c ?floor)
  hole:
  - (at ?c ?hole)
  - (last-at ?c ?hole)
  avatar:
  - (at ?c ?avatar)
  - (last-at ?c ?avatar)
  box:
  - (at ?c ?box)
  - (last-at ?c ?box)
  wall:
  - (at ?c ?wall)
  - (last-at ?c ?wall)
variablesTypes:
  ?floor: floor
  ?hole: hole
  ?avatar: avatar
  ?box: box
  ?wall: wall
  ?c: cell
cellVariable: ?c
avatarVariable: ?avatar
orientation:
  avatar: NONE
orientationCorrespondence:
  UP: (oriented-up ?object)
  DOWN: (oriented-down ?object)
  LEFT: (oriented-left ?object)
  RIGHT: (oriented-right ?object)
connections:
  UP: (connected-up ?c ?u)
  DOWN: (connected-down ?c ?d)
  LEFT: (connected-left ?c ?l)
  RIGHT: (connected-right ?c ?r)
actionsCorrespondence:
  AVATAR_ACTION_MOVE_UP: ACTION_UP
  AVATAR_ACTION_MOVE_DOWN: ACTION_DOWN
  AVATAR_ACTION_MOVE_LEFT: ACTION_LEFT
  AVATAR_ACTION_MOVE_RIGHT: ACTION_RIGHT
  AVATAR_ACTION_NIL: ACTION_NIL
additionalPredicates:
- (turn-avatar)
- (turn-sprites)
- (turn-interactions)
addDeadObjects: {}
goals: 
- goalPredicate: (turn-avatar)
  priority: 1
  saveGoal: no
