domainFile: domains/coordinates-based/sokoban.pddl
problemFile: problem.pddl
domainName: VGDLGame
gameElementsCorrespondence:
  hole:
  - (at ?n1 ?n2 ?hole)
  avatar:
  - (at ?n1 ?n2 ?avatar)
  box:
  - (at ?n1 ?n2 ?box)
  wall:
  - (is-wall ?n1 ?n2)
variablesTypes:
  ?hole: hole
  ?avatar: avatar
  ?box: box
  ?wall: wall
  ?n: num
numVariable: ?n
avatarVariable: ?avatar
orientation:
  avatar: NONE
orientationCorrespondence:
  UP: (oriented-up ?object)
  DOWN: (oriented-down ?object)
  LEFT: (oriented-left ?object)
  RIGHT: (oriented-right ?object)
connections:
  NEXT: (next ?n1 ?n2)
  PREVIOUS: (previous ?n1 ?n2)
actionsCorrespondence:
  AVATAR_ACTION_MOVE_UP: ACTION_UP
  AVATAR_ACTION_MOVE_DOWN: ACTION_DOWN
  AVATAR_ACTION_MOVE_LEFT: ACTION_LEFT
  AVATAR_ACTION_MOVE_RIGHT: ACTION_RIGHT
  AVATAR_ACTION_NIL: ACTION_NIL
additionalPredicates:
- (turn-avatar)
addDeadObjects: {}
goals: 
- goalPredicate: (turn-avatar)
  priority: 1
  saveGoal: no
