domainFile: domains/boulderdash-domain.pddl
problemFile: problem.pddl
domainName: BoulderDash
gameElementsCorrespondence:
  background:
  - (terrain-empty ?c)
  wall:
  - (terrain-wall ?c)
  sword:
  - (terrain-empty ?c)
  dirt:
  - (terrain-ground ?c)
  exitdoor:
  - (at ?e ?c)
  - (terrain-empty ?c)
  diamond:
  - (at ?g ?c)
  - (terrain-empty ?c)
  - (occupied ?c)
  boulder:
  - (at ?boulder ?c)
  - (terrain-empty ?c)
  - (occupied ?c)
  avatar:
  - (at ?p ?c)
  - (terrain-empty ?c)
  crab:
  - (at ?s ?c)
  - (terrain-empty ?c)
  - (occupied ?c)
  butterfly:
  - (at ?b ?c)
  - (terrain-empty ?c)
  - (occupied ?c)
variablesTypes:
  ?e: Exit
  ?p: Player
  ?boulder: Boulder
  ?g: Gem
  ?b: Bat
  ?s: Scorpion
  ?c: Cell
cellVariable: ?c
avatarVariable: ?p
orientationCorrespondence:
  UP: (oriented-up ?p)
  DOWN: (oriented-down ?p)
  LEFT: (oriented-left ?p)
  RIGHT: (oriented-right ?p)
connections:
  UP: (connected-up ?c ?u)
  DOWN: (connected-down ?c ?d)
  LEFT: (connected-left ?c ?l)
  RIGHT: (connected-right ?c ?r)
actionsCorrespondence:
  TURN-UP: ACTION_UP
  TURN-DOWN: ACTION_DOWN
  TURN-LEFT: ACTION_LEFT
  TURN-RIGHT: ACTION_RIGHT
  MOVE-UP: ACTION_UP
  MOVE-DOWN: ACTION_DOWN
  MOVE-LEFT: ACTION_LEFT
  MOVE-RIGHT: ACTION_RIGHT
  MOVE-UP-GET-GEM: ACTION_UP
  MOVE-DOWN-GET-GEM: ACTION_DOWN
  MOVE-LEFT-GET-GEM: ACTION_LEFT
  MOVE-RIGHT-GET-GEM: ACTION_RIGHT
  DIG-UP: ACTION_USE
  DIG-DOWN: ACTION_USE
  DIG-LEFT: ACTION_USE
  DIG-RIGHT: ACTION_USE
  EXIT-LEVEL: null
goals:
- goalPredicate: (got g_16_9)
  priority: 1
  saveGoal: no
- goalPredicate: (got g_7_3)
  priority: 1
  saveGoal: no
- goalPredicate: (got g_6_3)
  priority: 1
  saveGoal: no
- goalPredicate: (got g_5_3)
  priority: 1
  saveGoal: no
- goalPredicate: (got g_1_4)
  priority: 1
  saveGoal: no
- goalPredicate: (got g_6_1)
  priority: 1
  saveGoal: no
- goalPredicate: (got g_7_1)
  priority: 1
  saveGoal: no
- goalPredicate: (got g_7_9)
  priority: 1
  saveGoal: no
- goalPredicate: (got g_9_10)
  priority: 1
  saveGoal: no
- goalPredicate: (exited-level)
  priority: 2
  saveGoal: no
