domainFile: domains/ice-and-fire.pddl
problemFile: problem.pddl
domainName: VGDLGame
gameElementsCorrespondence:
  floor:
  - (at ?c ?floor)
  - (last-at ?c ?floor)
  exit:
  - (at ?c ?exit)
  - (last-at ?c ?exit)
  avatar:
  - (at ?c ?avatar)
  - (last-at ?c ?avatar)
  trap:
  - (at ?c ?trap)
  - (last-at ?c ?trap)
  ice:
  - (at ?c ?ice)
  - (last-at ?c ?ice)
  fire:
  - (at ?c ?fire)
  - (last-at ?c ?fire)
  feetwear:
  - (at ?c ?feetwear)
  - (last-at ?c ?feetwear)
  - (got-resource-feetwear ?feetwear)
  iceshoes:
  - (at ?c ?iceshoes)
  - (last-at ?c ?iceshoes)
  fireboots:
  - (at ?c ?fireboots)
  - (last-at ?c ?fireboots)
  chip:
  - (at ?c ?chip)
  - (last-at ?c ?chip)
  wall:
  - (at ?c ?wall)
  - (last-at ?c ?wall)
variablesTypes:
  ?floor: floor
  ?exit: exit
  ?avatar: avatar
  ?trap: trap
  ?ice: ice
  ?fire: fire
  ?feetwear: feetwear
  ?iceshoes: iceshoes
  ?fireboots: fireboots
  ?chip: chip
  ?wall: wall
  ?c: cell
cellVariable: ?c
avatarVariable: ?avatar
orientation:
  avatar: NONE
orientationCorrespondence:
  UP: (oriented-up ?object)
  DOWN: (oriented-down ?object)
  LEFT: (oriented-left ?object)
  RIGHT: (oriented-right ?object)
connections:
  UP: (connected-up ?c ?u)
  DOWN: (connected-down ?c ?d)
  LEFT: (connected-left ?c ?l)
  RIGHT: (connected-right ?c ?r)
actionsCorrespondence:
  AVATAR_ACTION_MOVE_UP: ACTION_UP
  AVATAR_ACTION_MOVE_DOWN: ACTION_DOWN
  AVATAR_ACTION_MOVE_LEFT: ACTION_LEFT
  AVATAR_ACTION_MOVE_RIGHT: ACTION_RIGHT
  AVATAR_ACTION_NIL: ACTION_NIL
additionalPredicates:
- (turn-avatar)
- (turn-sprites)
- (turn-interactions)
addDeadObjects: {}
goals: 
- goalPredicate: (turn-avatar)
  priority: 1
  saveGoal: no
