(define (problem VGDLGameProblem)
    (:domain VGDLGame)
    (:objects
        n0 n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 n11 n12 - num
    )
    (:init
        (is-wall n0 n0)
        (is-wall n1 n0)
        (is-wall n2 n0)
        (is-wall n3 n0)
        (is-wall n4 n0)
        (is-wall n5 n0)
        (is-wall n6 n0)
        (is-wall n7 n0)
        (is-wall n8 n0)
        (is-wall n9 n0)
        (is-wall n10 n0)
        (is-wall n11 n0)
        (is-wall n12 n0)
        (is-wall n0 n1)
        (is-wall n1 n1)
        (is-wall n2 n1)
        (is-wall n3 n1)
        (is-wall n4 n1)
        (is-wall n5 n1)
        (is-goal n6 n1)
        (is-wall n7 n1)
        (is-wall n8 n1)
        (is-wall n9 n1)
        (is-wall n10 n1)
        (is-wall n11 n1)
        (is-wall n12 n1)
        (is-wall n0 n2)
        (is-wall n1 n2)
        (is-wall n2 n2)
        (is-wall n3 n2)
        (is-wall n4 n2)
        (is-wall n8 n2)
        (is-wall n9 n2)
        (is-wall n10 n2)
        (is-wall n11 n2)
        (is-wall n12 n2)
        (is-wall n0 n3)
        (is-wall n4 n3)
        (avatar-oriented-none)
        (is-avatar n6 n3)
        (is-wall n8 n3)
        (is-wall n12 n3)
        (is-wall n0 n4)
        (is-box n2 n4)
        (is-box n10 n4)
        (is-wall n12 n4)
        (is-wall n0 n5)
        (is-wall n1 n5)
        (is-wall n2 n5)
        (is-wall n3 n5)
        (is-wall n4 n5)
        (is-hole n6 n5)
        (is-wall n8 n5)
        (is-wall n9 n5)
        (is-wall n10 n5)
        (is-wall n11 n5)
        (is-wall n12 n5)
        (is-wall n0 n6)
        (is-wall n1 n6)
        (is-wall n2 n6)
        (is-wall n3 n6)
        (is-wall n4 n6)
        (is-wall n5 n6)
        (is-hole n6 n6)
        (is-wall n7 n6)
        (is-wall n8 n6)
        (is-wall n9 n6)
        (is-wall n10 n6)
        (is-wall n11 n6)
        (is-wall n12 n6)
        (is-wall n0 n7)
        (is-wall n1 n7)
        (is-wall n2 n7)
        (is-wall n3 n7)
        (is-wall n4 n7)
        (is-wall n5 n7)
        (is-key n6 n7)
        (is-wall n7 n7)
        (is-wall n8 n7)
        (is-wall n9 n7)
        (is-wall n10 n7)
        (is-wall n11 n7)
        (is-wall n12 n7)
        (is-wall n0 n8)
        (is-wall n1 n8)
        (is-wall n2 n8)
        (is-wall n3 n8)
        (is-wall n4 n8)
        (is-wall n5 n8)
        (is-wall n6 n8)
        (is-wall n7 n8)
        (is-wall n8 n8)
        (is-wall n9 n8)
        (is-wall n10 n8)
        (is-wall n11 n8)
        (is-wall n12 n8)
        (next n0 n1)
        (next n1 n2)
        (next n2 n3)
        (next n3 n4)
        (next n4 n5)
        (next n5 n6)
        (next n6 n7)
        (next n7 n8)
        (next n8 n9)
        (next n9 n10)
        (next n10 n11)
        (next n11 n12)
        (previous n1 n0)
        (previous n2 n1)
        (previous n3 n2)
        (previous n4 n3)
        (previous n5 n4)
        (previous n6 n5)
        (previous n7 n6)
        (previous n8 n7)
        (previous n9 n8)
        (previous n10 n9)
        (previous n11 n10)
        (previous n12 n11)
        (turn-avatar)
        (got-resource-key n0)     
    )
    (:goal
        (AND
            (not (is-goal n6 n1))
        )
    )
)