(define (problem VGDLGameProblem)
    (:domain VGDLGame)
    (:objects
        redkey_11_9 - redkey
        mud1 - mud
        avatar - avatar
        fireboots_1_4 - fireboots
        crate_2_8 crate_9_8 - crate
        reddoor_3_2 - reddoor
        exit_1_1 - exit
        n0 n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 n11 n12 - num
    )
    (:init
        (is-wall n0 n0)
        (is-wall n1 n0)
        (is-wall n2 n0)
        (is-wall n3 n0)
        (is-wall n4 n0)
        (is-wall n5 n0)
        (is-wall n6 n0)
        (is-wall n7 n0)
        (is-wall n8 n0)
        (is-wall n9 n0)
        (is-wall n10 n0)
        (is-wall n11 n0)
        (is-wall n12 n0)
        (is-wall n0 n1)
        (at n1 n1 exit_1_1)
        (is-wall n3 n1)
        (is-wall n12 n1)
        (is-wall n0 n2)
        (at n3 n2 reddoor_3_2)
        (is-wall n12 n2)
        (is-wall n0 n3)
        (is-wall n1 n3)
        (is-wall n2 n3)
        (is-wall n3 n3)
        (is-wall n4 n3)
        (is-wall n5 n3)
        (is-wall n6 n3)
        (is-wall n7 n3)
        (is-wall n12 n3)
        (is-wall n0 n4)
        (at n1 n4 fireboots_1_4)
        (is-wall n2 n4)
        (is-wall n3 n4)
        (is-wall n4 n4)
        (is-wall n5 n4)
        (is-wall n6 n4)
        (is-wall n7 n4)
        (is-wall n8 n4)
        (is-wall n9 n4)
        (is-wall n10 n4)
        (is-fire n11 n4)
        (is-wall n12 n4)
        (is-wall n0 n5)
        (is-wall n12 n5)
        (is-wall n0 n6)
        (is-wall n1 n6)
        (is-wall n2 n6)
        (is-wall n3 n6)
        (is-wall n4 n6)
        (is-water n5 n6)
        (is-wall n6 n6)
        (is-wall n7 n6)
        (is-wall n8 n6)
        (is-wall n9 n6)
        (is-wall n10 n6)
        (is-wall n11 n6)
        (is-wall n12 n6)
        (is-wall n0 n7)
        (is-water n1 n7)
        (is-water n2 n7)
        (is-water n3 n7)
        (is-water n4 n7)
        (is-water n5 n7)
        (is-water n6 n7)
        (is-water n7 n7)
        (is-wall n8 n7)
        (is-wall n9 n7)
        (is-wall n10 n7)
        (is-wall n11 n7)
        (is-wall n12 n7)
        (is-wall n0 n8)
        (at n2 n8 crate_2_8)
        (at n9 n8 crate_9_8)
        (is-wall n12 n8)
        (is-wall n0 n9)
        (oriented-none avatar)
        (at n1 n9 avatar)
        (at n11 n9 redkey_11_9)
        (is-wall n12 n9)
        (is-wall n0 n10)
        (is-wall n1 n10)
        (is-wall n2 n10)
        (is-wall n3 n10)
        (is-wall n4 n10)
        (is-wall n5 n10)
        (is-wall n6 n10)
        (is-wall n7 n10)
        (is-wall n8 n10)
        (is-wall n9 n10)
        (is-wall n10 n10)
        (is-wall n11 n10)
        (is-wall n12 n10)
        (next n0 n1)
        (next n1 n2)
        (next n2 n3)
        (next n3 n4)
        (next n4 n5)
        (next n5 n6)
        (next n6 n7)
        (next n7 n8)
        (next n8 n9)
        (next n9 n10)
        (next n10 n11)
        (next n11 n12)
        (previous n1 n0)
        (previous n2 n1)
        (previous n3 n2)
        (previous n4 n3)
        (previous n5 n4)
        (previous n6 n5)
        (previous n7 n6)
        (previous n8 n7)
        (previous n9 n8)
        (previous n10 n9)
        (previous n11 n10)
        (previous n12 n11)
        (turn-avatar)
        (got-resource-redkey n0)
        (got-resource-bluekey n0)
        (got-resource-greenkey n0)
        (got-resource-yellowkey n0)
        (got-resource-flippers n0)
        (got-resource-fireboots n0)
        (got-resource-chip n0)
        (object-dead mud1)
    )
    (:goal
        (AND
            (forall (?o - exit) (object-dead ?o))
        )
    )
)