(define (problem VGDLGameProblem)
    (:domain VGDLGame)
    (:objects
        redkey_2_4 - redkey
        mud1 mud2 mud3 mud4 mud5 - mud
        avatar - avatar
        yellowdoor_6_1 - yellowdoor
        fireboots_1_3 - fireboots
        crate_6_3 crate_3_4 crate_4_4 crate_7_4 crate_2_5 crate_6_5 - crate
        yellowkey_3_3 - yellowkey
        bluedoor_5_1 - bluedoor
        reddoor_4_1 - reddoor
        exit_1_1 - exit
        bluekey_1_5 - bluekey
        n0 n1 n2 n3 n4 n5 n6 n7 n8 n9 - num
    )
    (:init
        (is-wall n0 n0)
        (is-wall n1 n0)
        (is-wall n2 n0)
        (is-wall n3 n0)
        (is-wall n4 n0)
        (is-wall n5 n0)
        (is-wall n6 n0)
        (is-wall n7 n0)
        (is-wall n8 n0)
        (is-wall n9 n0)
        (is-wall n0 n1)
        (at n1 n1 exit_1_1)
        (is-fire n2 n1)
        (at n4 n1 reddoor_4_1)
        (at n5 n1 bluedoor_5_1)
        (at n6 n1 yellowdoor_6_1)
        (is-wall n9 n1)
        (is-wall n0 n2)
        (is-wall n1 n2)
        (is-wall n2 n2)
        (is-wall n3 n2)
        (is-wall n5 n2)
        (is-wall n7 n2)
        (is-water n8 n2)
        (is-wall n9 n2)
        (is-wall n0 n3)
        (at n1 n3 fireboots_1_3)
        (is-water n2 n3)
        (at n3 n3 yellowkey_3_3)
        (at n6 n3 crate_6_3)
        (is-wall n9 n3)
        (is-wall n0 n4)
        (is-fire n1 n4)
        (at n2 n4 redkey_2_4)
        (at n3 n4 crate_3_4)
        (at n4 n4 crate_4_4)
        (is-fire n5 n4)
        (at n7 n4 crate_7_4)
        (is-wall n9 n4)
        (is-wall n0 n5)
        (at n1 n5 bluekey_1_5)
        (at n2 n5 crate_2_5)
        (is-water n3 n5)
        (is-water n4 n5)
        (is-water n5 n5)
        (at n6 n5 crate_6_5)
        (oriented-none avatar)
        (at n7 n5 avatar)
        (is-wall n9 n5)
        (is-wall n0 n6)
        (is-wall n1 n6)
        (is-wall n2 n6)
        (is-wall n3 n6)
        (is-wall n4 n6)
        (is-wall n5 n6)
        (is-wall n6 n6)
        (is-wall n7 n6)
        (is-wall n8 n6)
        (is-wall n9 n6)
        (next n0 n1)
        (next n1 n2)
        (next n2 n3)
        (next n3 n4)
        (next n4 n5)
        (next n5 n6)
        (next n6 n7)
        (next n7 n8)
        (next n8 n9)
        (previous n1 n0)
        (previous n2 n1)
        (previous n3 n2)
        (previous n4 n3)
        (previous n5 n4)
        (previous n6 n5)
        (previous n7 n6)
        (previous n8 n7)
        (previous n9 n8)
        (turn-avatar)
        (got-resource-redkey n0)
        (got-resource-bluekey n0)
        (got-resource-greenkey n0)
        (got-resource-yellowkey n0)
        (got-resource-flippers n0)
        (got-resource-fireboots n0)
        (got-resource-chip n0)
        (object-dead mud1)
        (object-dead mud2)
        (object-dead mud3)
        (object-dead mud4)
        (object-dead mud5)
    )
    (:goal
        (AND
            (object-dead exit_1_1)
        )
    )
)