domainFile: domains/dummy_baseline1.pddl
problemFile: problem.pddl
domainName: VGDLGame

# Hace falta incluir los objetos del juego específico ?
# - Leer objetos left-most objects en descripción VGDL
# - Añadir objetos devueltos por GVGAI
gameElementsCorrespondence:
  avatar:
  - (at ?c ?avatar)
variablesTypes:
  ?avatar: avatar
  ?c: cell

cellVariable: ?c
avatarVariable: ?avatar

# Esto habrá que modificarlo según el juego
orientation:
  avatar: NONE

orientationCorrespondence:
  UP: (oriented-up ?object)
  DOWN: (oriented-down ?object)
  LEFT: (oriented-left ?object)
  RIGHT: (oriented-right ?object)
connections:
  UP: (connected-up ?c ?u)
  DOWN: (connected-down ?c ?d)
  LEFT: (connected-left ?c ?l)
  RIGHT: (connected-right ?c ?r)
actionsCorrespondence:
  DO_NOTHING: ACTION_NIL
additionalPredicates: {}
addDeadObjects: {}

# Objetivo cualquiera ?
goals:
- goalPredicate: (connected-up n0 n1)
  priority: 1
  saveGoal: no