domainFile: domains/simplified-version/bait.pddl
problemFile: problem.pddl
domainName: VGDLGame
gameElementsCorrespondence:
  avatar:
  - (at ?x ?y ?avatar)
  hole:
  - (is-hole ?x ?y)
  mushroom:
  - (at ?x ?y ?mushroom)
  key:
  - (at ?x ?y ?key)
  goal:
  - (at ?x ?y ?goal)
  box:
  - (at ?x ?y ?box)
  wall:
  - (is-wall ?x ?y)
variablesTypes:
  ?avatar: avatar
  ?mushroom: mushroom
  ?key: key
  ?goal: goal
  ?box: box
  ?x: num
  ?y: num
avatarVariable: ?avatar
orientation:
  avatar: NONE
orientationCorrespondence:
  UP: (oriented-up ?object)
  DOWN: (oriented-down ?object)
  LEFT: (oriented-left ?object)
  RIGHT: (oriented-right ?object)
fluentsPredicates:
  next: (next ?n0 ?n1)
  previous: (previous ?n1 ?n0)
actionsCorrespondence:
  AVATAR_ACTION_MOVE_UP: ACTION_UP
  AVATAR_ACTION_MOVE_DOWN: ACTION_DOWN
  AVATAR_ACTION_MOVE_LEFT: ACTION_LEFT
  AVATAR_ACTION_MOVE_RIGHT: ACTION_RIGHT
additionalPredicates:
- (turn-avatar)
- (got-resource-key n0)
addDeadObjects: {}
goals:
- goalPredicate: (object-dead goal_1_1)
  priority: 1
  saveGoal: no
