domainFile: domains/domain.pddl
problemFile: problem.pddl
domainName: VGDLGame
gameElementsCorrespondence:
  avatar:
  - (at ?x ?y ?avatar)
  sword:
  - (at ?x ?y ?sword)
  exitdoor:
  - (at ?x ?y ?exitdoor)
  diamond:
  - (at ?x ?y ?diamond)
  - (got-resource-diamond n0)
  boulder:
  - (at ?x ?y ?boulder)
  moving:
  - (at ?x ?y ?moving)
  enemy:
  - (at ?x ?y ?enemy)
  crab:
  - (at ?x ?y ?crab)
  butterfly:
  - (at ?x ?y ?butterfly)
variablesTypes:
  ?sword: sword
  ?exitdoor: exitdoor
  ?diamond: diamond
  ?boulder: boulder
  ?moving: moving
  ?avatar: avatar
  ?enemy: enemy
  ?crab: crab
  ?butterfly: butterfly
  ?x: num
  ?y: num
avatarVariable: ?avatar
orientation:
  avatar: FIND
orientationCorrespondence:
  UP: (oriented-up ?object)
  DOWN: (oriented-down ?object)
  LEFT: (oriented-left ?object)
  RIGHT: (oriented-right ?object)
connections:
  UP: (connected-up ?c ?u)
  DOWN: (connected-down ?c ?d)
  LEFT: (connected-left ?c ?l)
  RIGHT: (connected-right ?c ?r)
actionsCorrespondence:
  AVATAR_ACTION_MOVE_UP: ACTION_UP
  AVATAR_ACTION_MOVE_DOWN: ACTION_DOWN
  AVATAR_ACTION_MOVE_LEFT: ACTION_LEFT
  AVATAR_ACTION_MOVE_RIGHT: ACTION_RIGHT
  AVATAR_ACTION_TURN_UP: ACTION_UP
  AVATAR_ACTION_TURN_DOWN: ACTION_DOWN
  AVATAR_ACTION_TURN_LEFT: ACTION_LEFT
  AVATAR_ACTION_TURN_RIGHT: ACTION_RIGHT
  AVATAR_ACTION_USE_UP: ACTION_USE
  AVATAR_ACTION_USE_DOWN: ACTION_USE
  AVATAR_ACTION_USE_LEFT: ACTION_USE
  AVATAR_ACTION_USE_RIGHT: ACTION_USE
additionalPredicates:
- (turn-avatar)
addDeadObjects:
  sword: 1
goals: []
