domainFile: domains/domain.pddl
problemFile: problem.pddl
domainName: VGDLGame
gameElementsCorrespondence:
  avatar:
  - (at ?x ?y ?avatar)
  cocoon:
  - (at ?x ?y ?cocoon)
  animal:
  - (at ?x ?y ?animal)
  butterfly:
  - (at ?x ?y ?butterfly)
  wall:
  - (is-wall ?x ?y)
variablesTypes:
  ?cocoon: cocoon
  ?animal: animal
  ?avatar: avatar
  ?butterfly: butterfly
  ?x: num
  ?y: num
avatarVariable: ?avatar
orientation:
  avatar: NONE
orientationCorrespondence:
  UP: (oriented-up ?object)
  DOWN: (oriented-down ?object)
  LEFT: (oriented-left ?object)
  RIGHT: (oriented-right ?object)
connections:
  UP: (connected-up ?c ?u)
  DOWN: (connected-down ?c ?d)
  LEFT: (connected-left ?c ?l)
  RIGHT: (connected-right ?c ?r)
actionsCorrespondence:
  AVATAR_ACTION_MOVE_UP: ACTION_UP
  AVATAR_ACTION_MOVE_DOWN: ACTION_DOWN
  AVATAR_ACTION_MOVE_LEFT: ACTION_LEFT
  AVATAR_ACTION_MOVE_RIGHT: ACTION_RIGHT
additionalPredicates:
- (turn-avatar)
addDeadObjects: {}
goals: []
