domainFile: domains/simplified-version/cakybaky.pddl
problemFile: problem.pddl
domainName: VGDLGame
gameElementsCorrespondence:
  avatar:
  - (at ?x ?y ?avatar)
  chef:
  - (is-chef ?x ?y)
  table:
  - (is-table ?x ?y)
  inca:
  - (at ?x ?y ?inca)
  incb:
  - (at ?x ?y ?incb)
  incc:
  - (at ?x ?y ?incc)
  incd:
  - (at ?x ?y ?incd)
  ince:
  - (at ?x ?y ?ince)
  incf:
  - (at ?x ?y ?incf)
  wall:
  - (is-wall ?x ?y)
variablesTypes:
  ?inca: inca
  ?incb: incb
  ?incc: incc
  ?incd: incd
  ?ince: ince
  ?incf: incf
  ?avatar: avatar
  ?x: num
  ?y: num
avatarVariable: ?avatar
orientation:
  avatar: FIND
orientationCorrespondence:
  UP: (oriented-up ?object)
  DOWN: (oriented-down ?object)
  LEFT: (oriented-left ?object)
  RIGHT: (oriented-right ?object)
fluentsPredicates:
  next: (next ?n0 ?n1)
  previous: (previous ?n1 ?n0)
actionsCorrespondence:
  AVATAR_ACTION_MOVE_UP: ACTION_UP
  AVATAR_ACTION_MOVE_DOWN: ACTION_DOWN
  AVATAR_ACTION_MOVE_LEFT: ACTION_LEFT
  AVATAR_ACTION_MOVE_RIGHT: ACTION_RIGHT
  AVATAR_ACTION_TURN_UP: ACTION_UP
  AVATAR_ACTION_TURN_DOWN: ACTION_DOWN
  AVATAR_ACTION_TURN_LEFT: ACTION_LEFT
  AVATAR_ACTION_TURN_RIGHT: ACTION_RIGHT
additionalPredicates:
- (turn-avatar)
- (got-resource-inca n0)
- (got-resource-incb n0)
- (got-resource-incc n0)
- (got-resource-incd n0)
- (got-resource-ince n0)
- (got-resource-incf n0)
addDeadObjects: {}
goals:
- goalPredicate: (at n14 n12 avatar)
  priority: 1
  saveGoal: no
