domainFile: domains/simplified-version/iceandfire.pddl
problemFile: problem.pddl
domainName: VGDLGame
gameElementsCorrespondence:
  avatar:
  - (at ?x ?y ?avatar)
  exit:
  - (at ?x ?y ?exit)
  trap:
  - (is-trap ?x ?y)
  ice:
  - (is-ice ?x ?y)
  fire:
  - (is-fire ?x ?y)
  iceshoes:
  - (at ?x ?y ?iceshoes)
  fireboots:
  - (at ?x ?y ?fireboots)
  wall:
  - (is-wall ?x ?y)
variablesTypes:
  ?exit: exit
  ?avatar: avatar
  ?iceshoes: iceshoes
  ?fireboots: fireboots
  ?x: num
  ?y: num
avatarVariable: ?avatar
orientation:
  avatar: NONE
orientationCorrespondence:
  UP: (oriented-up ?object)
  DOWN: (oriented-down ?object)
  LEFT: (oriented-left ?object)
  RIGHT: (oriented-right ?object)
fluentsPredicates:
  next: (next ?n0 ?n1)
  previous: (previous ?n1 ?n0)
actionsCorrespondence:
  AVATAR_ACTION_MOVE_UP: ACTION_UP
  AVATAR_ACTION_MOVE_DOWN: ACTION_DOWN
  AVATAR_ACTION_MOVE_LEFT: ACTION_LEFT
  AVATAR_ACTION_MOVE_RIGHT: ACTION_RIGHT
additionalPredicates:
- (turn-avatar)
- (got-resource-iceshoes n0)
- (got-resource-fireboots n0)
addDeadObjects: {}
goals:
- goalPredicate: (at n14 n12 avatar)
  priority: 1
  saveGoal: no