domainFile: domains/simplified-version/sokoban.pddl
problemFile: problem.pddl
domainName: VGDLGame
gameElementsCorrespondence:
  avatar:
  - (at ?x ?y ?avatar)
  hole:
  - (at ?x ?y ?hole)
  box:
  - (at ?x ?y ?box)
  wall:
  - (is-wall ?x ?y)
variablesTypes:
  ?hole: hole
  ?avatar: avatar
  ?box: box
  ?x: num
  ?y: num
avatarVariable: ?avatar
orientation:
  avatar: NONE
orientationCorrespondence:
  UP: (oriented-up ?object)
  DOWN: (oriented-down ?object)
  LEFT: (oriented-left ?object)
  RIGHT: (oriented-right ?object)
fluentsPredicates:
  next: (next ?n0 ?n1)
  previous: (previous ?n1 ?n0)
actionsCorrespondence:
  AVATAR_ACTION_MOVE_UP: ACTION_UP
  AVATAR_ACTION_MOVE_DOWN: ACTION_DOWN
  AVATAR_ACTION_MOVE_LEFT: ACTION_LEFT
  AVATAR_ACTION_MOVE_RIGHT: ACTION_RIGHT
additionalPredicates:
- (turn-avatar)
addDeadObjects: {}
goals:
- goalPredicate: (and (object-dead box_2_4) (object-dead box_3_4) (object-dead box_4_3))
  priority: 1
  saveGoal: no
# - goalPredicate: (object-dead box_3_4)
#   priority: 1
#   saveGoal: no
# - goalPredicate: (object-dead box_4_3)
#   priority: 1
#   saveGoal: no