domainFile: domains/simplified-version/zelda.pddl
problemFile: problem.pddl
domainName: VGDLGame
gameElementsCorrespondence:
  avatar:
  - (at ?x ?y ?avatar)
  goal:
  - (at ?x ?y ?goal)
  key:
  - (at ?x ?y ?key)
  sword:
  - (at ?x ?y ?sword)
  enemy:
  - (is-enemy ?x ?y)
  monsterQuick:
  - (at ?x ?y ?enemy)
  monsterNormal:
  - (at ?x ?y ?enemy)
  monsterSlow:
  - (at ?x ?y ?enemy)
  wall:
  - (is-wall ?x ?y)
variablesTypes:
  ?goal: goal
  ?key: key
  ?sword: sword
  ?avatar: avatar
  ?enemy: enemy
  ?x: num
  ?y: num
avatarVariable: ?avatar
orientation:
  avatar: FIND
orientationCorrespondence:
  UP: (oriented-up ?object)
  DOWN: (oriented-down ?object)
  LEFT: (oriented-left ?object)
  RIGHT: (oriented-right ?object)
fluentsPredicates:
  next: (next ?n0 ?n1)
  previous: (previous ?n1 ?n0)
actionsCorrespondence:
  AVATAR_ACTION_MOVE_UP: ACTION_UP
  AVATAR_ACTION_MOVE_DOWN: ACTION_DOWN
  AVATAR_ACTION_MOVE_LEFT: ACTION_LEFT
  AVATAR_ACTION_MOVE_RIGHT: ACTION_RIGHT
  AVATAR_ACTION_TURN_UP: ACTION_UP
  AVATAR_ACTION_TURN_DOWN: ACTION_DOWN
  AVATAR_ACTION_TURN_LEFT: ACTION_LEFT
  AVATAR_ACTION_TURN_RIGHT: ACTION_RIGHT
  AVATAR_ACTION_USE_UP: ACTION_USE
  AVATAR_ACTION_USE_DOWN: ACTION_USE
  AVATAR_ACTION_USE_LEFT: ACTION_USE
  AVATAR_ACTION_USE_RIGHT: ACTION_USE
additionalPredicates:
- (turn-avatar)
- (got-resource-key n0)
addDeadObjects:
  sword: 1
goals: []
